/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { POLICY_MULTISIG_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const VALIDATE_DISCRIMINATOR = new Uint8Array([
  60, 252, 90, 66, 246, 253, 232, 139,
]);

export function getValidateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(VALIDATE_DISCRIMINATOR);
}

export type ValidateInstruction<
  TProgram extends string = typeof POLICY_MULTISIG_PROGRAM_ADDRESS,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountPolicyAccount extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountTransaction extends string
        ? ReadonlyAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountPolicyAccount extends string
        ? WritableAccount<TAccountPolicyAccount>
        : TAccountPolicyAccount,
      TAccountSender extends string
        ? ReadonlyAccount<TAccountSender>
        : TAccountSender,
      TAccountSigner extends string
        ? ReadonlyAccount<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type ValidateInstructionData = { discriminator: ReadonlyUint8Array };

export type ValidateInstructionDataArgs = {};

export function getValidateInstructionDataEncoder(): FixedSizeEncoder<ValidateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: VALIDATE_DISCRIMINATOR })
  );
}

export function getValidateInstructionDataDecoder(): FixedSizeDecoder<ValidateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getValidateInstructionDataCodec(): FixedSizeCodec<
  ValidateInstructionDataArgs,
  ValidateInstructionData
> {
  return combineCodec(
    getValidateInstructionDataEncoder(),
    getValidateInstructionDataDecoder()
  );
}

export type ValidateInput<
  TAccountVault extends string = string,
  TAccountTransaction extends string = string,
  TAccountPolicyAccount extends string = string,
  TAccountSender extends string = string,
  TAccountSigner extends string = string,
> = {
  vault: Address<TAccountVault>;
  transaction: Address<TAccountTransaction>;
  policyAccount: Address<TAccountPolicyAccount>;
  sender: Address<TAccountSender>;
  signer: Address<TAccountSigner>;
};

export function getValidateInstruction<
  TAccountVault extends string,
  TAccountTransaction extends string,
  TAccountPolicyAccount extends string,
  TAccountSender extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof POLICY_MULTISIG_PROGRAM_ADDRESS,
>(
  input: ValidateInput<
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountSender,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): ValidateInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountTransaction,
  TAccountPolicyAccount,
  TAccountSender,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_MULTISIG_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: false },
    transaction: { value: input.transaction ?? null, isWritable: false },
    policyAccount: { value: input.policyAccount ?? null, isWritable: true },
    sender: { value: input.sender ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.policyAccount),
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.signer),
    ],
    programAddress,
    data: getValidateInstructionDataEncoder().encode({}),
  } as ValidateInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountTransaction,
    TAccountPolicyAccount,
    TAccountSender,
    TAccountSigner
  >;

  return instruction;
}

export type ParsedValidateInstruction<
  TProgram extends string = typeof POLICY_MULTISIG_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    transaction: TAccountMetas[1];
    policyAccount: TAccountMetas[2];
    sender: TAccountMetas[3];
    signer: TAccountMetas[4];
  };
  data: ValidateInstructionData;
};

export function parseValidateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedValidateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      transaction: getNextAccount(),
      policyAccount: getNextAccount(),
      sender: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getValidateInstructionDataDecoder().decode(instruction.data),
  };
}
