/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedValidateCreationInstruction,
  type ParsedValidateInstruction,
} from '../instructions';

export const POLICY_ALLOW_ANY_PROGRAM_ADDRESS =
  'BTS3xZ1DMoLp5jUXKeCCAKCY8jYySLwYUiKvW67wJBBJ' as Address<'BTS3xZ1DMoLp5jUXKeCCAKCY8jYySLwYUiKvW67wJBBJ'>;

export enum PolicyAllowAnyInstruction {
  Validate,
  ValidateCreation,
}

export function identifyPolicyAllowAnyInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyAllowAnyInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 252, 90, 66, 246, 253, 232, 139])
      ),
      0
    )
  ) {
    return PolicyAllowAnyInstruction.Validate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([112, 63, 138, 178, 246, 43, 119, 49])
      ),
      0
    )
  ) {
    return PolicyAllowAnyInstruction.ValidateCreation;
  }
  throw new Error(
    'The provided instruction could not be identified as a policyAllowAny instruction.'
  );
}

export type ParsedPolicyAllowAnyInstruction<
  TProgram extends string = 'BTS3xZ1DMoLp5jUXKeCCAKCY8jYySLwYUiKvW67wJBBJ',
> =
  | ({
      instructionType: PolicyAllowAnyInstruction.Validate;
    } & ParsedValidateInstruction<TProgram>)
  | ({
      instructionType: PolicyAllowAnyInstruction.ValidateCreation;
    } & ParsedValidateCreationInstruction<TProgram>);
