/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum DrawdownType {
  Static,
  Dynamic,
}

export type DrawdownTypeArgs = DrawdownType;

export function getDrawdownTypeEncoder(): FixedSizeEncoder<DrawdownTypeArgs> {
  return getEnumEncoder(DrawdownType);
}

export function getDrawdownTypeDecoder(): FixedSizeDecoder<DrawdownType> {
  return getEnumDecoder(DrawdownType);
}

export function getDrawdownTypeCodec(): FixedSizeCodec<
  DrawdownTypeArgs,
  DrawdownType
> {
  return combineCodec(getDrawdownTypeEncoder(), getDrawdownTypeDecoder());
}
