/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { POLICY_CHALLENGES_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getChallengeStatusDecoder,
  getChallengeStatusEncoder,
  getDailyDrawdownDecoder,
  getDailyDrawdownEncoder,
  getMaximumLossDecoder,
  getMaximumLossEncoder,
  getProfitTargetDecoder,
  getProfitTargetEncoder,
  getTradingDaysDecoder,
  getTradingDaysEncoder,
  type ChallengeStatus,
  type ChallengeStatusArgs,
  type DailyDrawdown,
  type DailyDrawdownArgs,
  type MaximumLoss,
  type MaximumLossArgs,
  type ProfitTarget,
  type ProfitTargetArgs,
  type TradingDays,
  type TradingDaysArgs,
} from '../types';

export const UPDATE_CHALLENGE_DISCRIMINATOR = new Uint8Array([
  189, 212, 76, 181, 2, 202, 238, 16,
]);

export function getUpdateChallengeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CHALLENGE_DISCRIMINATOR
  );
}

export type UpdateChallengeInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountChallengeTemplateAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountChallengeAccount extends string | AccountMeta<string> = string,
  TAccountSender extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountChallengeTemplateAccount extends string
        ? ReadonlyAccount<TAccountChallengeTemplateAccount>
        : TAccountChallengeTemplateAccount,
      TAccountChallengeAccount extends string
        ? WritableAccount<TAccountChallengeAccount>
        : TAccountChallengeAccount,
      TAccountSender extends string
        ? WritableSignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateChallengeInstructionData = {
  discriminator: ReadonlyUint8Array;
  challengeId: string;
  latestBalance: bigint;
  status: ChallengeStatus;
  profitTarget: ProfitTarget;
  tradingDays: TradingDays;
  maximumLoss: MaximumLoss;
  dailyDrawdown: DailyDrawdown;
  payout: bigint;
};

export type UpdateChallengeInstructionDataArgs = {
  challengeId: string;
  latestBalance: number | bigint;
  status: ChallengeStatusArgs;
  profitTarget: ProfitTargetArgs;
  tradingDays: TradingDaysArgs;
  maximumLoss: MaximumLossArgs;
  dailyDrawdown: DailyDrawdownArgs;
  payout: number | bigint;
};

export function getUpdateChallengeInstructionDataEncoder(): Encoder<UpdateChallengeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['challengeId', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['latestBalance', getU64Encoder()],
      ['status', getChallengeStatusEncoder()],
      ['profitTarget', getProfitTargetEncoder()],
      ['tradingDays', getTradingDaysEncoder()],
      ['maximumLoss', getMaximumLossEncoder()],
      ['dailyDrawdown', getDailyDrawdownEncoder()],
      ['payout', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_CHALLENGE_DISCRIMINATOR })
  );
}

export function getUpdateChallengeInstructionDataDecoder(): Decoder<UpdateChallengeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['challengeId', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['latestBalance', getU64Decoder()],
    ['status', getChallengeStatusDecoder()],
    ['profitTarget', getProfitTargetDecoder()],
    ['tradingDays', getTradingDaysDecoder()],
    ['maximumLoss', getMaximumLossDecoder()],
    ['dailyDrawdown', getDailyDrawdownDecoder()],
    ['payout', getU64Decoder()],
  ]);
}

export function getUpdateChallengeInstructionDataCodec(): Codec<
  UpdateChallengeInstructionDataArgs,
  UpdateChallengeInstructionData
> {
  return combineCodec(
    getUpdateChallengeInstructionDataEncoder(),
    getUpdateChallengeInstructionDataDecoder()
  );
}

export type UpdateChallengeInput<
  TAccountChallengeTemplateAccount extends string = string,
  TAccountChallengeAccount extends string = string,
  TAccountSender extends string = string,
> = {
  challengeTemplateAccount: Address<TAccountChallengeTemplateAccount>;
  challengeAccount: Address<TAccountChallengeAccount>;
  sender: TransactionSigner<TAccountSender>;
  challengeId: UpdateChallengeInstructionDataArgs['challengeId'];
  latestBalance: UpdateChallengeInstructionDataArgs['latestBalance'];
  status: UpdateChallengeInstructionDataArgs['status'];
  profitTarget: UpdateChallengeInstructionDataArgs['profitTarget'];
  tradingDays: UpdateChallengeInstructionDataArgs['tradingDays'];
  maximumLoss: UpdateChallengeInstructionDataArgs['maximumLoss'];
  dailyDrawdown: UpdateChallengeInstructionDataArgs['dailyDrawdown'];
  payout: UpdateChallengeInstructionDataArgs['payout'];
};

export function getUpdateChallengeInstruction<
  TAccountChallengeTemplateAccount extends string,
  TAccountChallengeAccount extends string,
  TAccountSender extends string,
  TProgramAddress extends Address = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
>(
  input: UpdateChallengeInput<
    TAccountChallengeTemplateAccount,
    TAccountChallengeAccount,
    TAccountSender
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateChallengeInstruction<
  TProgramAddress,
  TAccountChallengeTemplateAccount,
  TAccountChallengeAccount,
  TAccountSender
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? POLICY_CHALLENGES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    challengeTemplateAccount: {
      value: input.challengeTemplateAccount ?? null,
      isWritable: false,
    },
    challengeAccount: {
      value: input.challengeAccount ?? null,
      isWritable: true,
    },
    sender: { value: input.sender ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.challengeTemplateAccount),
      getAccountMeta(accounts.challengeAccount),
      getAccountMeta(accounts.sender),
    ],
    programAddress,
    data: getUpdateChallengeInstructionDataEncoder().encode(
      args as UpdateChallengeInstructionDataArgs
    ),
  } as UpdateChallengeInstruction<
    TProgramAddress,
    TAccountChallengeTemplateAccount,
    TAccountChallengeAccount,
    TAccountSender
  >;

  return instruction;
}

export type ParsedUpdateChallengeInstruction<
  TProgram extends string = typeof POLICY_CHALLENGES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    challengeTemplateAccount: TAccountMetas[0];
    challengeAccount: TAccountMetas[1];
    sender: TAccountMetas[2];
  };
  data: UpdateChallengeInstructionData;
};

export function parseUpdateChallengeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateChallengeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      challengeTemplateAccount: getNextAccount(),
      challengeAccount: getNextAccount(),
      sender: getNextAccount(),
    },
    data: getUpdateChallengeInstructionDataDecoder().decode(instruction.data),
  };
}
