/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { type ParsedTransferLamportsInstruction } from '../instructions';

export const DROPPER_PROGRAM_ADDRESS =
  '6NvUvdwfnNdf7abkU4F3WJokivp1V1QcxFyFbBhJmkAD' as Address<'6NvUvdwfnNdf7abkU4F3WJokivp1V1QcxFyFbBhJmkAD'>;

export enum DropperInstruction {
  TransferLamports,
}

export function identifyDropperInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): DropperInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([62, 53, 201, 68, 102, 134, 83, 103])
      ),
      0
    )
  ) {
    return DropperInstruction.TransferLamports;
  }
  throw new Error(
    'The provided instruction could not be identified as a dropper instruction.'
  );
}

export type ParsedDropperInstruction<
  TProgram extends string = '6NvUvdwfnNdf7abkU4F3WJokivp1V1QcxFyFbBhJmkAD',
> = {
  instructionType: DropperInstruction.TransferLamports;
} & ParsedTransferLamportsInstruction<TProgram>;
