/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedValidateCreationInstruction,
  type ParsedValidateInstruction,
} from '../instructions';

export const POLICY_DENY_ALL_PROGRAM_ADDRESS =
  '9QAeahKVUriMVmpYnnWTKBKjEbpsxoB2HmVmDr1MHDLM' as Address<'9QAeahKVUriMVmpYnnWTKBKjEbpsxoB2HmVmDr1MHDLM'>;

export enum PolicyDenyAllInstruction {
  Validate,
  ValidateCreation,
}

export function identifyPolicyDenyAllInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PolicyDenyAllInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 252, 90, 66, 246, 253, 232, 139])
      ),
      0
    )
  ) {
    return PolicyDenyAllInstruction.Validate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([112, 63, 138, 178, 246, 43, 119, 49])
      ),
      0
    )
  ) {
    return PolicyDenyAllInstruction.ValidateCreation;
  }
  throw new Error(
    'The provided instruction could not be identified as a policyDenyAll instruction.'
  );
}

export type ParsedPolicyDenyAllInstruction<
  TProgram extends string = '9QAeahKVUriMVmpYnnWTKBKjEbpsxoB2HmVmDr1MHDLM',
> =
  | ({
      instructionType: PolicyDenyAllInstruction.Validate;
    } & ParsedValidateInstruction<TProgram>)
  | ({
      instructionType: PolicyDenyAllInstruction.ValidateCreation;
    } & ParsedValidateCreationInstruction<TProgram>);
