/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getManagerFeeStructureDecoder,
  getManagerFeeStructureEncoder,
  type ManagerFeeStructure,
  type ManagerFeeStructureArgs,
} from '../types';

export const VAULT_DISCRIMINATOR = new Uint8Array([
  211, 8, 232, 43, 2, 152, 117, 119,
]);

export function getVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(VAULT_DISCRIMINATOR);
}

export type Vault = {
  discriminator: ReadonlyUint8Array;
  policyProgram: Address;
  seed: string;
  authority: Address;
  manager: Option<Address>;
  parentVault: Option<Address>;
  allocation: bigint;
  onchainBalance: bigint;
  offchainBalance: bigint;
  totalBalance: bigint;
  lastBalanceUpdate: bigint;
  highWaterMark: bigint;
  totalFeesPaid: bigint;
  managerFees: Option<ManagerFeeStructure>;
  createdAt: bigint;
  lastFeeCollection: bigint;
};

export type VaultArgs = {
  policyProgram: Address;
  seed: string;
  authority: Address;
  manager: OptionOrNullable<Address>;
  parentVault: OptionOrNullable<Address>;
  allocation: number | bigint;
  onchainBalance: number | bigint;
  offchainBalance: number | bigint;
  totalBalance: number | bigint;
  lastBalanceUpdate: number | bigint;
  highWaterMark: number | bigint;
  totalFeesPaid: number | bigint;
  managerFees: OptionOrNullable<ManagerFeeStructureArgs>;
  createdAt: number | bigint;
  lastFeeCollection: number | bigint;
};

export function getVaultEncoder(): Encoder<VaultArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['policyProgram', getAddressEncoder()],
      ['seed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['authority', getAddressEncoder()],
      ['manager', getOptionEncoder(getAddressEncoder())],
      ['parentVault', getOptionEncoder(getAddressEncoder())],
      ['allocation', getU64Encoder()],
      ['onchainBalance', getU64Encoder()],
      ['offchainBalance', getU64Encoder()],
      ['totalBalance', getU64Encoder()],
      ['lastBalanceUpdate', getU64Encoder()],
      ['highWaterMark', getU64Encoder()],
      ['totalFeesPaid', getU64Encoder()],
      ['managerFees', getOptionEncoder(getManagerFeeStructureEncoder())],
      ['createdAt', getU64Encoder()],
      ['lastFeeCollection', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VAULT_DISCRIMINATOR })
  );
}

export function getVaultDecoder(): Decoder<Vault> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['policyProgram', getAddressDecoder()],
    ['seed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['authority', getAddressDecoder()],
    ['manager', getOptionDecoder(getAddressDecoder())],
    ['parentVault', getOptionDecoder(getAddressDecoder())],
    ['allocation', getU64Decoder()],
    ['onchainBalance', getU64Decoder()],
    ['offchainBalance', getU64Decoder()],
    ['totalBalance', getU64Decoder()],
    ['lastBalanceUpdate', getU64Decoder()],
    ['highWaterMark', getU64Decoder()],
    ['totalFeesPaid', getU64Decoder()],
    ['managerFees', getOptionDecoder(getManagerFeeStructureDecoder())],
    ['createdAt', getU64Decoder()],
    ['lastFeeCollection', getU64Decoder()],
  ]);
}

export function getVaultCodec(): Codec<VaultArgs, Vault> {
  return combineCodec(getVaultEncoder(), getVaultDecoder());
}

export function decodeVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Vault, TAddress>;
export function decodeVault<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Vault, TAddress>;
export function decodeVault<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Vault, TAddress> | MaybeAccount<Vault, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVaultDecoder()
  );
}

export async function fetchVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Vault, TAddress>> {
  const maybeAccount = await fetchMaybeVault(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVault<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Vault, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVault(maybeAccount);
}

export async function fetchAllVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Vault>[]> {
  const maybeAccounts = await fetchAllMaybeVault(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVault(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Vault>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeVault(maybeAccount));
}
