/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreateTxInstruction,
  type ParsedExecuteTxInstruction,
  type ParsedInitializeManagerRegistryInstruction,
  type ParsedInitializeVaultInstruction,
  type ParsedIssueChildVaultInstruction,
  type ParsedPingInstruction,
  type ParsedRegisterManagerInstruction,
  type ParsedVerifyManagerInstruction,
} from '../instructions';

export const HYRO_PROTOCOL_PROGRAM_ADDRESS =
  'F21ZKUur1arCbN3R4tGzxV2Erfs23TyL2sGiPurWutzD' as Address<'F21ZKUur1arCbN3R4tGzxV2Erfs23TyL2sGiPurWutzD'>;

export enum HyroProtocolAccount {
  ManagerProfile,
  ManagerRegistry,
  Transaction,
  Vault,
}

export function identifyHyroProtocolAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): HyroProtocolAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([135, 12, 238, 243, 236, 32, 123, 52])
      ),
      0
    )
  ) {
    return HyroProtocolAccount.ManagerProfile;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([181, 78, 54, 100, 122, 86, 63, 114])
      ),
      0
    )
  ) {
    return HyroProtocolAccount.ManagerRegistry;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([11, 24, 174, 129, 203, 117, 242, 23])
      ),
      0
    )
  ) {
    return HyroProtocolAccount.Transaction;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 8, 232, 43, 2, 152, 117, 119])
      ),
      0
    )
  ) {
    return HyroProtocolAccount.Vault;
  }
  throw new Error(
    'The provided account could not be identified as a hyroProtocol account.'
  );
}

export enum HyroProtocolInstruction {
  CreateTx,
  ExecuteTx,
  InitializeManagerRegistry,
  InitializeVault,
  IssueChildVault,
  Ping,
  RegisterManager,
  VerifyManager,
}

export function identifyHyroProtocolInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): HyroProtocolInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([97, 223, 80, 153, 55, 13, 155, 12])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.CreateTx;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([249, 17, 145, 23, 12, 252, 17, 41])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.ExecuteTx;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([45, 38, 8, 215, 181, 198, 110, 202])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.InitializeManagerRegistry;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([48, 191, 163, 44, 71, 129, 63, 164])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.InitializeVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([77, 93, 95, 1, 227, 206, 201, 173])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.IssueChildVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([173, 0, 94, 236, 73, 133, 225, 153])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.Ping;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([104, 14, 206, 198, 57, 194, 90, 109])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.RegisterManager;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([61, 121, 49, 235, 68, 94, 106, 30])
      ),
      0
    )
  ) {
    return HyroProtocolInstruction.VerifyManager;
  }
  throw new Error(
    'The provided instruction could not be identified as a hyroProtocol instruction.'
  );
}

export type ParsedHyroProtocolInstruction<
  TProgram extends string = 'F21ZKUur1arCbN3R4tGzxV2Erfs23TyL2sGiPurWutzD',
> =
  | ({
      instructionType: HyroProtocolInstruction.CreateTx;
    } & ParsedCreateTxInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.ExecuteTx;
    } & ParsedExecuteTxInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.InitializeManagerRegistry;
    } & ParsedInitializeManagerRegistryInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.InitializeVault;
    } & ParsedInitializeVaultInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.IssueChildVault;
    } & ParsedIssueChildVaultInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.Ping;
    } & ParsedPingInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.RegisterManager;
    } & ParsedRegisterManagerInstruction<TProgram>)
  | ({
      instructionType: HyroProtocolInstruction.VerifyManager;
    } & ParsedVerifyManagerInstruction<TProgram>);
