/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { HYRO_PROTOCOL_PROGRAM_ADDRESS } from '../programs';

/** UnauthorizedAdmin: Unauthorized admin access. */
export const HYRO_PROTOCOL_ERROR__UNAUTHORIZED_ADMIN = 0x1770; // 6000

export type HyroProtocolError = typeof HYRO_PROTOCOL_ERROR__UNAUTHORIZED_ADMIN;

let hyroProtocolErrorMessages: Record<HyroProtocolError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  hyroProtocolErrorMessages = {
    [HYRO_PROTOCOL_ERROR__UNAUTHORIZED_ADMIN]: `Unauthorized admin access.`,
  };
}

export function getHyroProtocolErrorMessage(code: HyroProtocolError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (hyroProtocolErrorMessages as Record<HyroProtocolError, string>)[
      code
    ];
  }

  return 'Error message not available in production bundles.';
}

export function isHyroProtocolError<
  TProgramErrorCode extends HyroProtocolError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    HYRO_PROTOCOL_PROGRAM_ADDRESS,
    code
  );
}
