[package]
name = "policy_multisig"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build"]

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
]

[lints.rust.deprecated]
level = "allow"

[dependencies]
anchor-lang = "0.31.1" 
hyro_sdk = { path = "../../lib/hyro_sdk" }

[profile.release]
overflow-checks = true
